[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "components", Scope = "member", Target = "System_Info.CustomApplicationContext.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "<ProgresBar>k__BackingField", Scope = "member", Target = "System_Info.Controllers.Cpu.Core.#Dispose()", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "lockPlacement", Scope = "member", Target = "System_Info.CustomApplicationContext.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "pinToDesktop", Scope = "member", Target = "System_Info.CustomApplicationContext.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "exit", Scope = "member", Target = "System_Info.CustomApplicationContext.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "options", Scope = "member", Target = "System_Info.CustomApplicationContext.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "panelDrives", Scope = "member", Target = "System_Info.Controllers.Drives.DriveSpaceController.#Dispose()", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "formSideBar", Scope = "member", Target = "System_Info.CustomApplicationContext.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "cancelSource", Scope = "member", Target = "System_Info.Controllers.Drives.DriveSpaceController.#Dispose()", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "panelMemory", Scope = "member", Target = "System_Info.Controllers.Memory.MemoryController.#Dispose()", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "panelNetwork", Scope = "member", Target = "System_Info.Controllers.Network.NetworkController.#Dispose()", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "cancelSource", Scope = "member", Target = "System_Info.Controllers.Memory.MemoryController.#Dispose()", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "cancelSource", Scope = "member", Target = "System_Info.Controllers.Network.NetworkController.#Dispose()", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "<ProgresBar>k__BackingField", Scope = "member", Target = "System_Info.Controllers.Cpu.Core.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "panelNetwork", Scope = "member", Target = "System_Info.Controllers.Network.NetworkController.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "cancelSource", Scope = "member", Target = "System_Info.Controllers.Cpu.CPUController.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "panelCpu", Scope = "member", Target = "System_Info.Controllers.Cpu.CPUController.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "cancelSource", Scope = "member", Target = "System_Info.Controllers.Drives.DriveSpaceController.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "hddTotal", Scope = "member", Target = "System_Info.Controllers.Drives.DriveSpaceController.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "panelDrives", Scope = "member", Target = "System_Info.Controllers.Drives.DriveSpaceController.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "<ProgresBar>k__BackingField", Scope = "member", Target = "System_Info.Controllers.Drives.HDD.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "cancelSource", Scope = "member", Target = "System_Info.Controllers.Memory.MemoryController.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "panelMemory", Scope = "member", Target = "System_Info.Controllers.Memory.MemoryController.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "<ProgresBar>k__BackingField", Scope = "member", Target = "System_Info.Controllers.Memory.MemoryUse.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "cancelSource", Scope = "member", Target = "System_Info.Controllers.Network.NetworkController.#Dispose(System.Boolean)", Justification = "Is disposed with conditional null check (?)")]

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the
// Code Analysis results, point to "Suppress Message", and click
// "In Suppression File".
// You do not need to add suppressions to this file manually.